.github/workflows/sonar.yml
=> # 44 move codebase to subfolder

mrmap/MrMap/context_processors.py, mrmap/service/templates/service/base.html, mrmap/service/templates/service/views/wfs_tree.html, mrmap/service/templates/service/views/wms_tree.html
fix action buttons in detail view
=> closes 61: fix action buttons in detail view

.gitignore
this adds `.gitkeep` files to have the empty directories with user writable permissions.
=> Docker dev setup: fix permissions for mapserver, postgis and redis dirs

mrmap/MrMap/settings.py, mrmap/service/models.py
* fixes docuents error in _set_document_secured()
=> * fixes redirect after logout

mrmap/MrMap/decorators.py, mrmap/service/helper/epsg_api.py, mrmap/service/helper/ogc/operation_request_handler.py, mrmap/service/views.py
This changes should fix the following issues: https://github.com/mrmap-community/mrmap/issues/119 and https://github.com/mrmap-community/mrmap/issues/120
=> Fix bug in security proxy and alter epsg resolver to use new registry

mrmap/quality/managers.py, mrmap/quality/models.py, mrmap/quality/tables.py, mrmap/resourceNew/managers/metadata.py, mrmap/resourceNew/models/metadata.py, mrmap/resourceNew/tables/metadata.py
- Added new table view to quality tables. 
- Added this new view to DatasetMetadata table. 
-  Other minor changes
fixes #130 
please review @MrSnyder , @jokiefer , @armin11
=> 130: Add conformoty check information columns to dataset metadata table

.github/workflows/sonar.yml
=> modify sonar workflow with new docker-compose

.env.docs, .github/workflows/build_docs.yml, .github/workflows/publish_docs.yml, docs/requirements.txt, docs/source/_templates/versions.html, docs/source/conf.py, docs/source/development/getting-started.rst
=> 197 add versioning in docs

.github/workflows/build_docs.yml, .github/workflows/publish_docs.yml, docs/source/development/project-structure.rst
=> describe  the new project structure

docs/source/features/index.rst, docs/source/features/users.rst, docs/source/index.rst
add gherkin feature files to documentation
* fixes #171
=> Update index.rst, users.rst, and index.rst

.github/workflows/build_docs.yml, .github/workflows/publish_docs.yml, docs/requirements.txt, docs/source/conf.py
fixes current branch detection
=> 5 migrate to bs5

mrmap/registry/templates/registry/mapcontext/mapcontext_form.html, mrmap/registry/templates/registry/mapcontext/mapcontext_layer_form.html
=> hotfix for missing form media

.run/appserver.run.xml, mrmap/registry/api/serializers/metadata.py, mrmap/registry/api/serializers/service.py
- Added serialized keywords to Service serializer. 
- Added dataset metadata resource api url to feature_types and layers Serializers. 
- Added feature_types and layers resource api url to dataset metadata Serializer
Fixes #239
=> SearchInterface: Coupled Resources are part of response

backend/extras/tasks.py, backend/locale/de/LC_MESSAGES/django.po, backend/registry/managers/metadata.py, backend/registry/managers/service.py, backend/registry/tasks/conformity.py, backend/registry/tasks/harvest.py, backend/registry/tasks/security.py, backend/registry/tasks/service.py, backend/registry/views/service.py
fixes collect metadata records task
=> fixes collect metadata

.github/workflows/quality-assurance.yml, frontend/src/Components/OgcService/OgcServiceAdd.tsx, frontend/src/Repos/OgcServiceRepo.ts, frontend/src/utils.tsx
Adds:
- ESLint check to github workflow
- Client unit testing  to github workflow
=> added stages to quality assurance workflow

docker/frontend/Dockerfile
This is a temporary solution until #306 is solved.
=> Added workaround for react-geo dependency issues to Dockerfile

backend/requirements.dev.txt, backend/requirements.txt
=> update all python packages to the newest possible version

docker-compose.yml, docker/backend/Dockerfile
fixes #337
* upgrade from python:3.9.7 to python:3.10.1
* upgrade from postgis:13-3.1 to postgis:14-3.1
=> upgrade docker container

backend/sonar-project.properties
=> excludes coverage reports from loc counting

frontend/src/App.tsx, frontend/src/index.tsx
See screenshot
Changes:
- Moved `WebSockets` component to below `RequireAuth`
=> Frontend: Fix 'WebSocket connection failed' message

backend/registry/serializers/mapcontext.py, backend/tests/behave/api/features/registry/mapcontext/mapcontextlayer/move_mapcontextlayers.feature, docker/nginx/mrmap.dev.conf, frontend/src/Components/MapContextEditor/LayerSettingsForm/LayerSettingsForm.tsx, frontend/src/Components/MapContextEditor/MapContextEditor.tsx, frontend/src/Components/MapContextEditor/MapContextLayerRepoForm/MapContextLayerRepoForm.tsx, frontend/src/Components/MapContextEditor/MapContextLayerTree/MapContextLayerTree.tsx, frontend/src/Components/Shared/BottomDrawer/BottomDrawer.tsx, frontend/src/Components/Shared/RepoForm/RepoForm.tsx, frontend/src/Components/WmsSecuritySettings/RulesDrawer/RulesDrawer.css, frontend/src/Components/WmsSecuritySettings/RulesDrawer/RulesDrawer.tsx, frontend/src/Components/WmsSecuritySettings/RulesDrawer/RulesTable/RulesTable.tsx
Changes:
- `MapContextSerializer`: Fix corner case for moving nodes, added tests.
- `MapContextEditor`: Improvements
=> Housekeeping: Rework mapcontext editor

backend/extras/openapi.py
* fixes required attribute on sort param
=> fixes boolean field which was interpreted as string

backend/registry/urls.py, backend/registry/views/metadata.py
=> fixes duplicate nested metadata contact lists

frontend/src/pages/user/Login/index.tsx
Changes:
- Use side effect with isAuthenticated dependency for forwarding instead of timeout.
- Disable username/password fields while logging in.
- Display loading indicator in login button.
=> Improve UX of Login component

frontend/config/defaultSettings.ts, frontend/src/app.tsx, frontend/src/components/RootContainer/index.tsx, frontend/src/pages/user/Login/index.tsx
* fixes multiple user patching
* fixes layout settings update (bug: overwrite on login)
=> fix user settings update routines in frontend

backend/MrMap/settings.py, backend/locale/de/LC_MESSAGES/django.po, backend/requirements.dev.txt, backend/requirements.txt, docker-compose.yml, docker/backend/Dockerfile, docker/nginx/Dockerfile, docker/nginx/Dockerfile.dev
migrate to newer python packages:
* django 4.1.3
* django-channels 4.0.0
* djangorestframework-jsonapi 6.0.0
and all depending packages as well
migrate docker container versions:
* redis 7.0.0
* nginx 1.23
=> House keeping/python package update

.github/workflows/publish_docs.yml, .github/workflows/quality-assurance.yml
=> Update publish_docs.yml and quality-assurance.yml

.github/workflows/publish_docs.yml
=> Migrate GitHub actions

mrmap/.requirements/base.txt, mrmap/MrMap/urls.py, mrmap/registry/apps.py, mrmap/registry/models/metadata.py, mrmap/registry/models/service.py, mrmap/registry/proxy/wfs_proxy.py, mrmap/registry/serializers/metadata.py, mrmap/registry/serializers/service.py, mrmap/registry/urls.py, mrmap/registry/views/metadata.py, mrmap/tests/django/registry/mrmap-proxy/tests_wfs_proxy.py, mrmap/tests/django/registry/mrmap-proxy/tests_wms_proxy.py
=> Epsg api proxy
